---
- name: create user mongod
  user:
    name: mongod
    groups: svc
    shell: /sbin/nologin
    create_home: false

# - name: apt install needed packages
#   apt:
#     name: jq
#     update_cache: yes
#     state: latest

- name: install mongodb binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: mongodb
      pkg_version: "{{ mongodb_version }}"
      pkg_url: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-{{ mongodb_version }}.tgz
      pkg_type: tgz
      creates: bin
      extracts: yes

- name: copy app files
  copy:
    src: opt/app/current/
    dest: /opt/app/current/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=
  
- name: install confd files
  include_role:
    name: confd-files-1.1.0